### ISSUE TITLE
Error: Call to undefined method Fisharebest\Webtrees\Repository::fullNames()

### ISSUE THREAD

**Issue by hartenthaler** [08ah15/WeEt#11]
When calling the module there is an error:
```
Call to undefined method Fisharebest\Webtrees\Repository::fullNames() …/modules_v4/WeEt/MyListModule.php:388
#0 …/modules_v4/WeEt/MyListModule.php(310): MyListNamespace\MyListModule->allArchives()
```

**Comment by 08ah15** [comment]
Thanks for highlighting. Give it a try with version 0.0.3.4

**Comment by hartenthaler** [comment]
Now there is a new error: ParseError: syntax error, unexpected token ";", expecting "function" or "const" in /.../webtreestest/modules_v4/WeEt/MyListModule.php:390 Stack trace: #0

**Comment by 08ah15** [comment]
Grrr...
I "solved" this one too and get a new one. I just do not understand why it work on my test setup but does not on the production machine. Obviously I am not doing the transfer well. Maybe the week after next week I find time to take a look again.

**Comment by 08ah15** [comment]
A good sleep and 15 pulls later…. At least you see a result.
